version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4576:4576"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - "SERVICES=sqs"
      - "DEFAULT_REGION=eu-west-1"
      - "HOSTNAME=${LOCALSTACK_HOSTNAME:-localhost}"
      - "HOSTNAME_EXTERNAL=${LOCALSTACK_HOSTNAME_EXTERNAL:-localhost}"

  create_localstack_resources:
    image: quay.io/signal/localstack-sidecar:0.1
    environment:
      #if localstack uses proxy mode (enabled by default) the internal service port should be specified.
      - LISTENING_PORT=4561 
      - LISTENING_HOST=localstack
    depends_on:
      - localstack
    links:
      - "localstack"
    volumes:
      - "./init:/opt/init"
